### ISSUE TITLE
rendering issues on android 13 and adreno 730

### ISSUE THREAD

**Issue by kde-yyds** [tareksander/termux-gfx-wrapper#11]
![Screenshot_2023-07-13-15-00-17-400_com.termux.x11.jpg](https://github.com/tareksander/termux-gfx-wrapper/assets/106876912/49155dd9-c1ca-4c2f-84a1-7c4c6676e48f)

![Screenshot_2023-07-13-14-59-22-836_com.termux.x11.jpg](https://github.com/tareksander/termux-gfx-wrapper/assets/106876912/d7a955eb-f29b-47dd-879e-095787b3f948)

**Comment by tareksander** [comment]
Try setting `TERMUX_EGL_DISABLE_HWBUF`, hardware buffer rendering isn't tested yet.

**Comment by kde-yyds** [comment]
ok,thanks
